"""initial

Revision ID: cf03b5218efd
Revises: 
Create Date: 2023-07-18 20:19:15.377582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf03b5218efd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controllers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('datetime', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controllers_datetime'), 'controllers', ['datetime'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controllers_datetime'), table_name='controllers')
    op.drop_table('controllers')
    # ### end Alembic commands ###
